header handles flags, especially the fuzzy flag
arashm/PoParser pull request #13
Opened 2016-12-14 17:22 UTC by dfherr

i'm not 100% sure, please double check, but this should fix the fuzzy header issue

2016-12-17 16:11 UTC, arashm requested changes

2016-12-17 16:11 UTC, arashm commented on spec/poparser/po_spec.rb
> +      puts @po.header.flag.class
Please remove these two `puts` lines.

2016-12-17 16:11 UTC, arashm commented on lib/poparser/header.rb
> +      @flag = entry.flag
Please align the equal with others.

2016-12-17 16:11 UTC, arashm commented on lib/poparser/header.rb
> +
Extra new line here. Please remove one of them.

2016-12-22 20:46 UTC, dfherr commented
added the requested changes

2016-12-27 08:29 UTC, merged